inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  # We don't always use bundler to make for a faster boot time.
  # In this case we vendor a small number of dependencies we absolutely
  # require. Since they are vendored and 3rd party we do not impose our
  # styleguide on them but they are still in the repo.
  Exclude:
    - db/**/*
    - Gemfile
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*
    - .git/**/*
    - tests/**/*
    - .bundle/**
    - example/**
    - .venv/**

  # Mac OS High Sierra ships with Ruby 2.3.x
  # Therefore we target Ruby 2.3
  TargetRubyVersion: 2.3

# We disable this at entrypoint.
# Due to CLI apps being invoked via an entry point,
# we can exclude this from all files
Style/FrozenStringLiteralComment:
  Enabled: true

# This doesn't take into account retrying from an exception. E.g.:
#   begin
#     retries ||= 0
#     do_a_thing
#   rescue => e
#     retry if (retries += 1) < 3
#     handle_error(e)
#   end
Lint/HandleExceptions:
  Enabled: true

# Allow readable block formatting in some weird cases
# Particularly in something like:
#   Dev::Util.begin do
#     might_raise_if_costly_prep_not_done()
#   end.retry_after(ExpectedError) do
#     costly_prep()
#   end
Style/MultilineBlockChain:
  Enabled: true

# Our extensive use of blocks in our CLI apps means that it is more
# expessive and easier to read a block var name than a random yield
Performance/RedundantBlockCall:
  Enabled: false

CyclomaticComplexity:
  Enabled: true

PerceivedComplexity:
  Enabled: true
